spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
logging:
  level:
    org.jooq: debug