spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
logging:
  level:
    org.jooq: debug